version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "lang/**",
  "vendor/**",
  "node_modules/**",
  "tmp/**"
]

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "php"
enabled = true